"""
GaryPOWER Signal Scanner
Ported from Pine Script v6 by Gary
Detects conditionA: days > 1000 AND since_last_gt100[1] > 100
Sends HTML email via Resend when signals are found.
"""

import os
import sys
import json
import requests
import numpy as np
import pandas as pd
import yfinance as yf
from datetime import datetime
from zoneinfo import ZoneInfo  # 必须引入这个

# ═══════════════════════════════════════════════════════════════════
#  WATCHLIST
# ═══════════════════════════════════════════════════════════════════

WATCHLIST = [
    # ─── ETF ─────────────────────────────────────────────────
    ("TQQQ", "纳指100三倍做多"),
    ("COWZ", "罗素1000自由现金流ETF"),
    # ─── 美股核心 ─────────────────────────────────────────────────
    ("MU", "美光科技"),
    ("SNDK", "闪迪"),
    ("SPCX", "SpaceX"),
    ("NVDA", "英伟达"),
    ("MRNA", "Moderna"),
    ("TSLA", "特斯拉"),
    ("WMT", "沃尔玛"),
    ("AAPL", "苹果"),
    ("INTC", "英特尔"),
    ("AMD", "美国超微公司"),
    ("NBIS", "NEBIUS"),
    ("MRVL", "迈威尔科技"),
    ("META", "Meta Platforms"),
    ("AVGO", "博通"),
    ("AMZN", "亚马逊"),
    ("MSFT", "微软"),
    ("MSTR", "Strategy"),
    ("GOOGL", "谷歌-A"),
    ("PLTR", "Palantir"),
    ("SKHY", "SK海力士"),
    ("GOOG", "谷歌-C"),
    ("LITE", "Lumentum"),
    ("COIN", "Coinbase"),
    ("STX", "希捷科技"),
    ("HOOD", "Robinhood"),
    ("WDC", "西部数据"),
    ("SMCI", "超微电脑"),
    ("AMAT", "应用材料"),
    ("NFLX", "奈飞"),
    ("COST", "好市多"),
    ("CRWV", "CoreWeave"),
    ("CRWD", "CrowdStrike"),
    ("TEM", "Tempus AI"),
    ("IREN", "IREN Ltd"),
    ("CBRS", "Cerebras Systems"),
    ("PANW", "Palo Alto Networks"),
    ("ASML", "阿斯麦"),
    ("LRCX", "泛林集团"),
    ("ISRG", "直觉外科公司"),
    ("DASH", "DoorDash"),
    ("AAOI", "Applied Optoelectronics"),
    ("APP", "Applovin"),
    ("RKLB", "Rocket Lab"),
    ("CSCO", "思科"),
    ("CRNX", "Crinetics"),
    ("KLAC", "科磊"),
    ("TEAM", "Atlassian"),
    ("TXN", "德州仪器"),
    ("ADI", "亚德诺"),
    ("AAL", "美国航空"),
    ("MARA", "MARA Holdings"),
    ("SOFI", "SoFi Technologies"),
    ("QCOM", "高通"),
    ("ABNB", "爱彼迎"),
    ("INTU", "财捷"),
    ("ROST", "罗斯百货"),
    ("AMGN", "安进"),
    ("PYPL", "PayPal"),
    ("CRDO", "Credo Technology"),
    ("MELI", "MercadoLibre"),
    ("SHOP", "Shopify"),
    ("LIN", "林德气体"),
    ("ILMN", "Illumina"),
    ("ARM", "Arm Holdings"),
    ("ONDS", "Ondas"),
    ("ADBE", "Adobe"),
    ("PEP", "百事可乐"),
    ("SBUX", "星巴克"),
    ("AXTI", "AXT Inc"),
    ("DDOG", "Datadog"),
    ("GILD", "吉利德科学"),
    ("TMUS", "T-Mobile US"),
    ("ALAB", "Astera Labs"),
    ("EBAY", "eBay"),
    ("CIFR", "Cipher Digital"),
    ("BKNG", "Booking Holdings"),
    ("FUTU", "富途控股"),
    ("ASTS", "AST SpaceMobile"),
    ("TER", "泰瑞达"),
    ("PURR", "HYPERLIQUID STRATEGIES INC"),
    ("BULL", "微牛"),
    ("HBAN", "亨廷顿银行"),
    ("MAR", "万豪酒店"),
    ("HONA", "Honeywell Aerospace"),
    ("STLD", "Steel Dynamics"),
    ("NTRA", "Natera"),
    ("DXCM", "德康医疗"),
    ("WULF", "TeraWulf"),
    ("TTWO", "Take-Two互动软件"),
    ("RIOT", "Riot Platforms"),
    ("WDAY", "Workday"),
    ("PDD", "拼多多"),
    ("UAL", "联合大陆航空"),
    ("CEG", "Constellation Energy"),
    ("MDB", "MongoDB"),
    ("HON", "霍尼韦尔"),
    ("ORLY", "奥莱利"),
    ("BNTX", "BioNTech"),
    ("CHTR", "特许通讯"),
    ("FTNT", "飞塔信息"),
    ("BIDU", "百度"),
    ("WBD", "Warner Bros Discovery"),
    ("APLD", "Applied Digital"),
    ("AXON", "Axon Enterprise"),
    ("IOVA", "Iovance Biotherapeutics"),
    ("NDSN", "Nordson"),
    ("NTAP", "美国网存"),
    ("HUT", "Hut 8"),
    ("ALNY", "阿里拉姆制药"),
    ("FANG", "Diamondback Energy"),
    ("SNPS", "新思科技"),
    ("CMCSA", "康卡斯特"),
    ("CDNS", "铿腾电子"),
    ("BKR", "Baker Hughes"),
    ("SGLY", "Singularity Future Technology"),
    ("ON", "安森美半导体"),
    ("LULU", "Lululemon Athletica"),
    ("RGTI", "Rigetti Computing"),
    ("CDW", "CDW Corp"),
    ("TWST", "Twist Bioscience"),
    ("CLSK", "CleanSpark"),
    ("EQIX", "易昆尼克斯"),
    ("MPWR", "Monolithic Power Systems"),
    ("ZS", "Zscaler"),
    ("REGN", "再生元制药公司"),
    ("GH", "Guardant Health"),
    ("VRTX", "福泰制药"),
    ("AMLX", "Amylyx Pharmaceuticals"),
    ("OKTA", "Okta"),
    ("CTAS", "信达思"),
    ("CME", "芝加哥商品交易所"),
    ("ADP", "自动数据处理"),
    ("MCHP", "微芯科技"),
    ("NXPI", "恩智浦"),
    ("FBRX", "Forte Biosciences"),
    ("CPRT", "科帕特"),
    ("HUIZ", "慧择"),
    ("RGEN", "Repligen"),
    ("BTCT", "BTC Digital"),
    ("PSNL", "Personalis"),
    ("FLEX", "伟创力"),
    ("FSLR", "第一太阳能"),
    ("DPZ", "达美乐比萨"),
    ("XEL", "埃克西尔能源"),
    ("RIVN", "Rivian Automotive"),
    ("ADSK", "欧特克"),
    ("CSX", "CSX运输"),
    ("ARGX", "argenx SE"),
    ("AVAV", "AeroVironment"),
    ("MNST", "怪物饮料"),
    ("TLN", "Talen Energy"),
    ("APA", "阿帕奇石油"),
    ("FTAI", "FTAI Aviation"),
    ("BTDR", "Bitdeer Technologies Group"),
    ("CELH", "Celsius Holdings"),
    ("FISV", "费哲金融服务"),
    ("MKTX", "MarketAxess"),
    ("UPST", "Upstart"),
    ("CPB", "金宝公司"),
    ("STRL", "Sterling Infrastructure"),
    ("USAR", "USA Rare Earth"),
    ("WWD", "伍德沃德"),
    ("IDXX", "爱德士"),
    ("KTOS", "克瑞拓斯安全防卫"),
    ("CTSH", "高知特"),
    ("MDLZ", "亿滋"),
    ("PCAR", "帕卡"),
    ("KDP", "Keurig Dr Pepper"),
    ("FCEL", "燃料电池能源"),
    ("RVMD", "Revolution Medicines"),
    ("EXE", "Expand Energy"),
    ("KHC", "卡夫亨氏"),
    ("KMB", "金佰利"),
    ("VICR", "Vicor电子"),
    ("QBTS", "D-Wave Quantum"),
    ("PAYX", "沛齐"),
    ("CORZ", "Core Scientific"),
    ("SMTC", "先科电子"),
    ("IBKR", "盈透证券"),
    ("TECH", "Bio-Techne"),
    ("AEHR", "Aehr Test Systems"),
    ("EXPE", "Expedia"),
    ("CSGP", "科斯塔"),
    ("FIVE", "Five Below"),
    ("ECHO", "回声星通信"),
    ("GMAB", "Genmab"),
    ("FWONK", "Liberty Formula One-C"),
    ("CASY", "Caseys General Stores"),
    ("CART", "Maplebear"),
    ("AMKR", "艾马克技术"),
    ("TSEM", "Tower半导体"),
    ("GLPI", "Gaming & Leisure Properties"),
    ("TTMI", "TTM科技"),
    ("DLTR", "美元树公司"),
    ("DKNG", "DraftKings"),
    ("MDLN", "Medline"),
    ("MKSI", "MKS仪器"),
    ("TSCO", "拖拉机供应公司"),
    ("AKAM", "阿克迈"),
    ("FAST", "快扣"),
    ("JZ", "见知教育"),
    ("TXG", "10x Genomics"),
    ("NTNX", "Nutanix"),
    ("INSM", "Insmed"),
    ("CRSP", "CRISPR Therapeutics"),
    ("SWKS", "思佳讯"),
    ("MANH", "Manhattan Associates"),
    ("NTES", "网易"),
    ("SITM", "SiTime"),
    ("FOXA", "福克斯公司-A"),
    ("MTSI", "MACOM Technology Solutions"),
    ("BLZE", "Backblaze"),
    ("PRAX", "Praxis Precision Medicines"),
    ("ASST", "Strive"),
    ("ALM", "Almonty Industries"),
    ("MWH", "SOLV Energy"),
    ("STRC", "STRATEGY INC VAR RT SER A PERP STRETCH PREFERRED STK"),
    ("WETO", "Wetour Robotics"),
    ("AUR", "Aurora Innovation"),
    ("SOUN", "SoundHound AI"),
    ("NTRS", "北方信托"),
    ("HIVE", "HIVE Digital Technologies"),
    ("TTD", "The Trade Desk"),
    ("APGE", "Apogee Therapeutics"),
    ("CAKE", "芝乐坊餐馆"),
    ("AEP", "美国电力"),
    ("ZM", "Zoom通讯"),
    ("ULTA", "Ulta美容"),
    ("ROP", "儒博实业"),
    ("CHYM", "Chime Financial"),
    ("AFRM", "Affirm Holdings"),
    ("ZBRA", "斑马技术"),
    ("RPRX", "Royalty Pharma"),
    ("ROKU", "Roku Inc"),
    ("JD", "京东"),
    ("TRMB", "天宝导航公司"),
    ("ENTG", "英特格"),
    ("WYNN", "永利度假村"),
    ("FIGR", "Figure Technology Solutions"),
    ("ODFL", "Old Dominion Freight Line"),
    ("SANM", "新美亚电子"),
    ("BBIO", "BridgeBio Pharma"),
    ("NDAQ", "纳斯达克"),
    ("MEDP", "Medpace"),
    ("TRI", "汤森路透"),
    ("AGNC", "美国资本代理公司"),
    ("EOSE", "Eos Energy"),
    ("GYGY", "Game Your Game"),
    ("GLXY", "Galaxy Digital"),
    ("TW", "Tradeweb Markets"),
    ("JBLU", "捷蓝航空"),
    ("EXC", "爱克斯龙电力"),
    ("LUNR", "Intuitive Machines"),
    ("JBHT", "JB亨特运输服务"),
    ("VRSK", "Verisk分析"),
    ("NXT", "Nextpower"),
    ("GFS", "GlobalFoundries"),
    ("LNTH", "Lantheus"),
    ("LYFT", "Lyft Inc"),
    ("EVRG", "西星能源"),
    ("UTHR", "美国联合医疗"),
    ("JKHY", "杰克亨利"),
    ("VIAV", "Viavi Solutions"),
    ("CAI", "Caris Life Sciences"),
    ("ASND", "Ascendis Pharma A/S"),
    ("SIMO", "慧荣科技"),
    ("LPLA", "LPL Financial"),
    ("SHAZ", "SharonAI Holdings"),
    ("SOLS", "Solstice Advanced Materials"),
    ("SNY", "赛诺菲安万特"),
    ("PODD", "银休特"),
    ("MXL", "MaxLinear"),
    ("WIX", "Wix.com"),
    ("GEHC", "GE HealthCare Technologies"),
    ("TPG", "TPG Inc"),
    ("BIVI", "BioVie"),
    ("KEEL", "Keel Infrastructure"),
    ("INIO", "INNIO N.V"),
    ("SBET", "SharpLink"),
    ("TGTX", "TG Therapeutics"),
    ("SSRM", "SSR Mining"),
    ("SLS", "Sellas Life Sciences"),
    ("TTEK", "德照科技"),
    ("QS", "QuantumScape"),
    ("BRZE", "Braze"),
    ("HST", "美国豪斯特酒店"),
    ("HALO", "奥洛兹美医疗"),
    ("RYAAY", "Ryanair"),
    ("CHRW", "罗宾逊物流"),
    ("GEN", "Gen Digital"),
    ("NVTS", "纳微半导体"),
    ("INCY", "因塞特"),
    ("SFM", "Sprouts Farmers Market"),
    ("MRVI", "Maravai LifeSciences"),
    ("RGLD", "皇家黄金"),
    ("WTW", "韦莱韬悦"),
    ("BIIB", "渤健公司"),
    ("ACGL", "艾奇资本"),
    ("IPST", "IP Strategy"),
    ("FROG", "JFrog"),
    ("OPEN", "Opendoor Technologies"),
    ("MDGL", "Madrigal Pharmaceuticals"),
    ("VRSN", "威瑞信"),
    ("GRAL", "Grail"),
    ("CYTK", "Cytokinetics"),
    ("ABVX", "Abivax S.A."),
    ("ALGN", "艾利科技"),
    ("FLNC", "Fluence Energy"),
    ("CCEP", "可口可乐欧洲太平洋"),
    ("DAVE", "Dave Inc"),
    ("LSCC", "莱迪思半导体"),
    ("FSLY", "Fastly"),
    ("CROX", "卡骆驰"),
    ("PLUG", "普拉格能源"),
    ("OUST", "Ouster"),
    ("IONS", "Ionis Pharmaceuticals"),
    ("BTBT", "Bit Digital"),
    ("URBN", "都市服饰"),
    ("LOGI", "罗技"),
    ("LQDA", "Liquidia"),
    ("WING", "Wingstop"),
    ("CHRD", "Chord Energy"),
    ("PTC", "PTC Inc"),
    ("RARE", "Ultragenyx Pharmaceutical"),
    ("AEIS", "先进能源工业"),
    ("MRCY", "Mercury Systems"),
    ("AUGO", "Aura Minerals"),
    ("XE", "X-Energy"),
    ("AXSM", "Axsome Therapeutics"),
    ("FER", "Ferrovial SE"),
    ("RITR", "域塔物流科技"),
    ("NBIX", "神经分泌生物科学"),
    ("VSAT", "卫讯公司"),
    ("STKH", "Steakholder Foods"),
    ("CENX", "世纪铝业"),
    ("LNT", "美国联合能源"),
    ("TTAN", "ServiceTitan"),
    ("DUOL", "多邻国"),
    ("LCID", "Lucid Group"),
    ("PENG", "Penguin Solutions"),
    ("GTLB", "Gitlab"),
    ("ENPH", "Enphase Energy"),
    ("GRAB", "Grab Holdings"),
    ("ATAT", "亚朵"),
    ("NVMI", "Nova"),
    ("ROIV", "Roivant Sciences"),
    ("LKQ", "LKQ Corp"),
    ("TIGO", "Millicom International Cellular"),
    ("EQPT", "EquipmentShare.com"),
    ("TCOM", "携程网"),
    ("BTSG", "BrightSpring Health Services"),
    ("PSKY", "Paramount Skydance"),
    ("TXRH", "德州公路酒吧"),
    ("FFIV", "F5 Inc"),
    ("TROW", "普信集团"),
    ("ZION", "齐昂银行"),
    ("BRLS", "Borealis Foods"),
    ("WYFI", "WhiteFiber"),
    ("MTCH", "Match group"),
    ("OLLI", "Ollie's Bargain Outlet"),
    ("CDTG", "城道通环保科技"),
    ("COLB", "哥伦比亚银行系统"),
    ("FCNCA", "第一公民银行股份"),
    ("FRMI", "Fermi"),
    ("BRKR", "布鲁克"),
    ("RXRX", "Recursion Pharmaceuticals"),
    ("DOCU", "DocuSign"),
    ("SGRY", "Surgery Partners"),
    ("FLY", "Firefly Aerospace"),
    ("JAZZ", "爵士制药"),
    ("HYMC", "Hycroft Mining"),
    ("RMBS", "Rambus"),
    ("FRPT", "Freshpet"),
    ("HTFL", "Heartflow"),
    ("PGY", "Pagaya Technologies"),
    ("QNT", "Quantinuum"),
    ("CACC", "Credit Acceptance"),
    ("ALGM", "Allegro Microsystems"),
    ("EXEL", "伊克力西斯"),
    ("CHKP", "Check Point软件"),
    ("KSPI", "Kaspi.kz"),
    ("CORT", "Corcept医疗"),
    ("CVLT", "康沃系统"),
    ("SATA", "STRIVE INC PERP PFD SER A VAR RATE"),
    ("UCTT", "超科林半导体"),
    ("ABCL", "AbCellera Biologics"),
    ("SEZL", "Sezzle"),
    ("ICLR", "Icon PLC"),
    ("ARQT", "Arcutis Biotherapeutics"),
    ("IESC", "IES Holdings"),
    ("HTHT", "华住"),
    ("LOOP", "Loop Industries"),
    ("VNOM", "Viper Energy"),
    ("GGAL", "加利西亚金融"),
    ("XOS", "Xos Inc"),
    ("DFTX", "Definium Therapeutics"),
    ("SMMT", "Summit Therapeutics"),
    ("BZ", "BOSS直聘"),
    ("QUBT", "Quantum Computing"),
    ("LECO", "林肯电气"),
    ("CG", "凯雷"),
    ("BEAM", "Beam Therapeutics"),
    ("CCC", "CCC Intelligent Solutions Holdings"),
    ("VISN", "Vistance Networks"),
    ("CRUS", "凌云半导体"),
    ("SCSC", "ScanSource"),
    ("VTRS", "Viatris"),
    ("HAS", "孩之宝"),
    ("XP", "XP Inc"),
    ("PFG", "信安金融"),
    ("ORKA", "Oruka Therapeutics"),
    ("GOOGN", "ALPHABET INC DEP SHS REPSTG 1/20TH INT B"),
    ("HQY", "HealthEquity"),
    ("FRVO", "Fervo Energy"),
    ("IRTC", "iRhythm Technologies"),
    ("VLY", "硅谷国家银行"),
    ("MFP", "Midera Food Processing"),
    ("SEDG", "SolarEdge Technologies"),
    ("CALM", "Cal-Maine Foods"),
    ("RCAT", "Red Cat Holdings"),
    ("DNTH", "Dianthus Therapeutics"),
    ("PCLA", "PicoCELA"),
    ("ONB", "Old National Bancorp"),
    ("ARCC", "阿瑞斯"),
    ("PTEN", "Patterson-UTI Energy"),
    ("ETOR", "eToro Group"),
    ("CGNX", "康耐视"),
    ("SBAC", "SBA通信公司"),
    ("COO", "库珀医疗"),
    ("COGT", "Cogent Biosciences"),
    ("ARWR", "Arrowhead Pharmaceuticals"),
    ("BILI", "哔哩哔哩"),
    ("PTGX", "Protagonist Therapeutics"),
    ("LAMR", "拉马尔户外广告"),
    ("POWL", "Powell Industries"),
    ("NTLA", "Intellia Therapeutics"),
    ("EXLS", "伊克赛尔服务"),
    ("SSNC", "SS&C Technologies"),
    ("REPL", "Replimune"),
    ("GLNG", "Golar LNG"),
    ("FORM", "FormFactor"),
    ("MYRG", "MYR Group"),
    ("IBRX", "ImmunityBio"),
    ("SAIA", "Saia"),
    ("SEIC", "SEI Investments"),
    ("KLIC", "库力索法半导体"),
    ("MMSI", "Merit Medical Systems"),
    ("ONC", "百济神州"),
    ("RELY", "Remitly Global"),
    ("CHDN", "Churchill Downs"),
    ("Z", "Zillow-C"),
    ("BMRN", "拜玛林制药"),
    ("APPF", "Appfolio"),
    ("NOVT", "Novanta"),
    ("SYRE", "Spyre Therapeutics"),
    ("COKE", "可口可乐装瓶"),
    ("LFUS", "美国力特保险丝"),
    ("POOL", "Pool Corp"),
    ("ATAI", "AtaiBeckley"),
    ("ACMR", "ACM Research"),
    ("NXTT", "Next Technology"),
    ("PONY", "小马智行"),
    ("CAPR", "Capricor Therapeutics"),
    ("VSEC", "VSE技术服务"),
    ("AAON", "艾伦建材"),
    ("TVTX", "Travere Therapeutic"),
    ("QLYS", "科力斯"),
    ("POET", "POET Technologies"),
    ("BLLN", "BillionToOne"),
    ("QRVO", "Qorvo"),
    ("PAA", "Plains All American Pipeline"),
    ("RUN", "Sunrun"),
    ("ASO", "Academy"),
    ("RYTM", "Rhythm Pharmaceuticals"),
    ("BSY", "Bentley Systems"),
    ("SYM", "Symbotic"),
    ("ERIC", "爱立信"),
    ("COLM", "哥伦比亚户外"),
    ("OCTV", "Octave Intelligence"),
    ("NWSA", "新闻集团-A"),
    ("SHC", "Sotera Health Company"),
    ("KYMR", "Kymera Therapeutics"),
    ("QURE", "uniQure NV"),
    ("DJCO", "每日期刊"),
    ("MEOH", "梅思恩"),
    ("SRRK", "Scholar Rock"),
    ("MORN", "晨星"),
    ("LEGN", "传奇生物"),
    ("GSAT", "全球星"),
    ("NVAX", "诺瓦瓦克斯医药"),
    ("REG", "Regency Centers Corp."),
    ("VKTX", "Viking Therapeutics"),
    ("AVT", "安富利"),
    ("ELVN", "Enliven Therapeutics"),
    ("OMH", "Ohmyhome"),
    ("RLAY", "Relay Therapeutics"),
    ("AMBA", "安霸"),
    ("SIRI", "Sirius XM"),
    ("MNDY", "monday.com"),
    ("SLAB", "芯科实验室"),
    ("FRHC", "Freedom Holding"),
    ("ENSG", "恩赛因"),
    ("LIF", "Life360"),
    ("VCTR", "Victory Capital"),
    ("AUPH", "Aurinia Pharmaceuticals"),
    ("CZR", "凯撒娱乐"),
    ("GDS", "万国数据"),
    ("ESLT", "埃尔比特系统"),
    ("LIFE", "Ethos Technologies"),
    ("INOD", "Innodata"),
    ("URGN", "乌龙制药"),
    ("UMBF", "UMB金融"),
    ("ATRO", "Astronics"),
    ("HSAI", "禾赛"),
    ("BPOP", "大众银行"),
    ("SAIC", "Science Applications International"),
    ("GOOGM", "ALPHABET INC DEP SHS REPSTG 1/20TH INT A"),
    ("SHLS", "Shoals Technologies"),
    ("IDCC", "InterDigital"),
    ("COCO", "Vita Coco"),
    ("HSIC", "汉瑞祥"),
    ("GPCR", "硕迪生物"),
    ("BYND", "Beyond Meat"),
    ("ALHC", "Alignment Healthcare"),
    ("FIVN", "Five9"),
    ("PTCT", "PTC Therapeutics"),
    ("MCHPP", "MICROCHIP TECHNOLOGY DEP SHS REPSTG 1/20TH PFD CONV SER A"),
    ("ALGT", "忠诚旅游"),
    ("EYPT", "EyePoint"),
    ("DBX", "Dropbox"),
    ("KRYS", "Krystal Biotech"),
    ("MGNI", "Magnite"),
    ("VERA", "Vera Therapeutics"),
    ("CINF", "辛辛纳提金融"),
    ("EWBC", "华美银行"),
    ("AXGN", "AxoGen"),
    ("MIDD", "The Middleby"),
    ("PGEN", "Precigen"),
    ("IPGP", "IPG光电"),
    ("SBLK", "Star Bulk Carriers"),
    ("OSIS", "OSI Systems"),
    ("UFPT", "UFP技术"),
    ("ATRC", "AtriCure"),
    ("NESR", "National Energy Services Reunited"),
    ("ARCB", "ArcBest"),
    ("ALKS", "阿尔凯默斯"),
    ("BHF", "Brighthouse Financial"),
    ("CVCO", "卡寇工业"),
    ("NXST", "Nexstar Media Group"),
    ("NCI", "思宏国际"),
    ("CRML", "Critical Metals"),
    ("ICUI", "ICU医疗"),
    ("CAMT", "康特科技"),
    ("CGON", "CG Oncology"),
    ("FCFS", "第一富金融服务"),
    ("YJ", "云集"),
    ("IRDM", "铱星通讯"),
    ("CELC", "Celcuity"),
    ("MBLY", "Mobileye Global"),
    ("PPC", "Pilgrim's Pride"),
    ("DOX", "Amdocs"),
    ("ALOY", "REalloys"),
    ("LOPE", "大峡谷教育"),
    ("NEO", "NeoGenomics"),
    ("WEN", "温蒂汉堡"),
    ("ADPT", "Adaptive Biotechnologies"),
    ("TMDX", "TransMedics"),
    ("BEEM", "Beam Global"),
    ("ERIE", "伊瑞保险"),
    ("FHB", "First Hawaiian"),
    ("STNE", "StoneCo"),
    ("ERAS", "Erasca"),
    ("PCTY", "Paylocity"),
    ("ZLAB", "再鼎医药"),
    ("IDYA", "IDEAYA生物科学"),
    ("LGN", "Legence"),
    ("PSMT", "普尔斯玛特"),
    ("BELFA", "Bel Fuse-A"),
    ("SYNA", "Synaptics"),
    ("BBNX", "Beta Bionics"),
    ("CCXI", "Churchill Capital Corp XI"),
    ("HLNE", "Hamilton Lane"),
    ("ARRY", "Array Technologies"),
    ("LASR", "nLIGHT"),
    ("CLDX", "塞德斯医疗"),
    ("GTX", "Garrett Motion"),
    ("TNGX", "Tango Therapeutics"),
    ("VSNT", "Versant Media"),
    ("VCYT", "Veracyte"),
    ("PEGA", "Pegasystems"),
    ("CBSH", "科默斯银行"),
    ("DJT", "特朗普媒体科技集团"),
    ("WTFC", "信达金融"),
    ("XNCR", "Xencor"),
    ("DIOD", "Diodes"),
    ("PCVX", "Vaxcyte"),
    ("EEFT", "嘉银通"),
    ("SRPT", "Sarepta Therapeutics"),
    ("GRPN", "GroupOn"),
    ("HTZ", "赫兹租车"),
    ("HWC", "汉考克惠特尼"),
    ("NAVN", "Navan"),
    ("CECO", "CECO环保"),
    ("NN", "NextNav"),
    ("ECPG", "安可资本"),
    ("HUBG", "Hub Group"),
    ("AYA", "Aya Gold & Silver"),
    ("GT", "固特异轮胎橡胶"),
    ("SAIL", "SailPoint"),
    ("FRSH", "Freshworks"),
    ("ICHR", "Ichor Holdings"),
    ("PLAB", "福尼克斯"),
    ("CSIQ", "阿特斯太阳能"),
    ("LGND", "Ligand Pharmaceuticals"),
    ("IMVT", "Immunovant"),
    ("INDV", "Indivior"),
    ("NCNO", "nCino"),
    ("ZG", "Zillow-A"),
    ("WSC", "WillScot Holdings"),
    ("CHEF", "The Chefs' Warehouse"),
    ("DLO", "DLocal"),
    ("QDEL", "窥得儿医药"),
    ("PCT", "PureCycle Technologies"),
    ("WFRD", "Weatherford国际"),
    ("CDNA", "CareDx"),
    ("IOND", "IONIC DIGITAL INC"),
    ("BATRK", "Atlanta Braves-C"),
    ("ZBIO", "Zenas BioPharma"),
    ("OTEX", "Open Text"),
    ("SHOO", "史蒂夫·马登"),
    ("QMCO", "昆腾"),
    ("FTDR", "Frontdoor"),
    ("ETON", "Eton Pharmaceutical"),
    ("DYN", "戴纳基"),
    ("VOD", "沃达丰"),
    ("AVAH", "Aveanna Healthcare"),
    ("CMPS", "COMPASS Pathways"),
    ("BSP", "Bending Spoons S.p.A"),
    ("DSGX", "笛卡尔物流系统集团"),
    ("ROAD", "Construction Partners"),
    ("CAST", "FreeCast"),
    ("MRX", "Marex Group"),
    ("SBCF", "Seacoast Bank"),
    ("SLM", "学贷美"),
    ("FOX", "福克斯公司-B"),
    ("FSV", "Firstservice"),
    ("TENB", "Tenable Holdings"),
    ("BLTE", "Belite Bio"),
    ("WB", "微博"),
    ("WMG", "华纳音乐"),
    ("XRAY", "登士柏"),
    ("VNET", "世纪互联"),
    ("GNTX", "真泰克"),
    ("POWI", "帕沃英蒂格盛"),
    ("HURN", "休伦咨询"),
    ("SKWD", "Skyward Specialty Insurance"),
    ("PENN", "佩恩国民博彩"),
    ("AGYS", "阿吉赛斯"),
    ("MAT", "美泰"),
    ("KC", "金山云"),
    ("GSHD", "Goosehead Insurance"),
    ("XENE", "Xenon制药"),
    ("OLED", "Universal Display"),
    ("COHU", "科休半导体"),
    ("PLPC", "Preformed Line Products"),
    ("CLBT", "Cellebrite"),
    ("EWTX", "Edgewise Therapeutics"),
    ("WGS", "GeneDx Holdings"),
    ("TCBI", "Texas Capital Bancshares"),
    ("PATK", "Patrick Industries"),
    ("PLXS", "普雷克萨斯"),
    ("GEMI", "Gemini Space Station"),
    ("PPTA", "Perpetua Resources"),
    ("NTSK", "Netskope"),
    ("LSTR", "莱帝运输"),
    ("LYTS", "LSI设备"),
    ("NKTR", "内克塔治疗"),
    ("ESTA", "Establishment Labs"),
    ("DGII", "美国迪进国际"),
    ("PTRN", "Pattern Group"),
    ("BELFB", "Bel Fuse-B"),
    ("TNDM", "Tandem Diabetes Care"),
    ("OPCH", "Option Care Health"),
    ("MGN", "Megan"),
    ("NNE", "NANO Nuclear Energy"),
    ("MNPR", "Monopar Therapeutics"),
    ("BRUN", "Boost Run"),
    ("OCUL", "Ocular Therapeutix"),
    ("TRIP", "猫途鹰"),
    ("OMER", "奥麦罗制药"),
    ("ABSI", "Absci Corp"),
    ("LAES", "SEALSQ Corp"),
    ("NWL", "纽威"),
    ("KALU", "凯撒铝业"),
    ("EBC", "Eastern Bankshares"),
    ("INDI", "indie Semiconductor"),
    ("FIBK", "First Interstate BancSystem"),
    ("NICE", "NICE Ltd"),
    ("LPTH", "LightPath Technologies"),
    ("ENVX", "Enovix"),
    ("TARS", "Tarsus Pharmaceuticals"),
    ("OZK", "欧扎克银行"),
    ("VRNS", "Varonis系统"),
    ("ARCT", "Arcturus Therapeutics"),
    ("CLMT", "卡路美"),
    ("ACAD", "阿卡迪亚"),
    ("CBRL", "CB乡村店"),
    ("LINC", "林肯教育服务"),
    ("BLBD", "Blue Bird"),
    ("SNEX", "StoneX"),
    ("QFIN", "奇富科技"),
    ("ORBS", "Eightco Holdings"),
    ("LI", "理想汽车"),
    ("SFD", "Smithfield Foods"),
    ("PZZA", "棒约翰"),
    ("SUPN", "Supernus Pharmaceuticals"),
    ("UBSI", "联合银行"),
    ("TIGR", "向上融科"),
    ("PRCT", "PROCEPT BioRobotics"),
    ("HIFS", "欣厄姆银行"),
    ("PECO", "Phillips Edison"),
    ("RDNT", "RadNet"),
    ("LAUR", "Laureate Education"),
    ("PI", "Impinj"),
    ("ACIW", "ACI环球"),
    ("AEVA", "Aeva Technologies"),
    ("NSIT", "Insight Enterprises"),
    ("INBX", "Inhibrx Biosciences"),
    ("MMED", "MiniMed Group"),
    ("PVLA", "Palvella Therapeutics"),
    ("FULT", "富尔顿金融"),
    ("CEVA", "CEVA Inc"),
    ("PAGP", "Plains GP Holdings"),
    ("MIRM", "Mirum Pharmaceuticals"),
    ("LIVN", "LivaNova"),
    ("WRLD", "环球验收"),
    ("HAPN", "Happen Inc"),
    ("WAY", "Waystar Holding"),
    ("MZTI", "Marzetti"),
    ("ABTC", "American Bitcoin"),
    ("MBX", "MBX Biosciences"),
    ("PHVS", "Pharvaris"),
    ("DXPE", "DXP Enterprises"),
    ("NRIX", "Nurix Therapeutics"),
    ("WYHG", "荣业食品"),
    ("HELP", "Cybin"),
    ("EWAV", "East West Ave Acquisition Corp"),
    ("GLBE", "Global-E Online"),
    ("PPLI", "People"),
    ("IMNM", "Immunome"),
    ("KURA", "Kura Oncology"),
    ("REAL", "TheRealReal"),
    ("BLFS", "BioLife Solutions"),
    ("DVLT", "Datavault AI"),
    ("ITRI", "伊管"),
    ("SIGI", "Selective Insurance"),
    ("NUAI", "New Era Energy & Digital"),
    ("BTTC", "Black Titan"),
    ("KNSA", "Kiniksa Pharmaceuticals International"),
    ("PGNY", "Progyny"),
    ("INTA", "Intapp"),
    ("ALNT", "Allient"),
    ("MLAB", "Mesa Laboratories"),
    ("JBSS", "John B. Sanfilippo & Son"),
    ("LFST", "LifeStance Health"),
    ("SKYW", "西空航空"),
    ("BAND", "Bandwidth"),
    ("WERN", "沃纳企业"),
    ("STEP", "StepStone Group"),
    ("SPSC", "SPS Commerce"),
    ("ACHC", "阿卡迪亚医疗保健"),
    ("PNRG", "PrimeEnergy Resources"),
    ("BGC", "BGC Group"),
    ("LGCL", "罗科仕"),
    ("VC", "伟世通"),
    ("UFPI", "UFP Industries"),
    ("STOK", "Stoke Therapeutics"),
    ("PTON", "Peloton Interactive"),
    ("JOYY", "欢聚"),
    ("SSYS", "Stratasys"),
    ("SATL", "Satellogic"),
    ("AZTA", "Azenta"),
    ("CADL", "Candel Therapeutics"),
    ("CAN", "嘉楠科技"),
    ("MMYT", "MakeMyTrip"),
    ("RUSHA", "Rush Enterprises-A"),
    ("FGL", "FOUNDER GROUP LIMITED"),
    ("XMTR", "Xometry"),
    ("HRMY", "Harmony Biosciences"),
    ("CLBK", "Columbia Financial"),
    ("CAR", "安飞士"),
    ("DRS", "Leonardo DRS, Inc."),
    ("TRVI", "Trevi Therapeutics"),
    ("BLKB", "布莱克波特科技"),
    ("MRAM", "Everspin Technologies"),
    ("APPS", "Digital Turbine"),
    ("BOKF", "BOK银行"),
    ("USLM", "美国灰矿建材"),
    ("SBRA", "Sabra Health Care REIT"),
    ("TLRY", "Tilray Brands"),
    ("INDB", "美国独立银行"),
    ("IMMX", "Immix Biopharma"),
    ("RXT", "Rackspace Technology"),
    ("DNLI", "Denali Therapeutics"),
    ("RRR", "Red Rock Resorts"),
    ("THEO", "BOA Acquisition Corp II"),
    ("LILAK", "Liberty Latin America-C"),
    ("NUTX", "Nutex Health"),
    ("JBIO", "Jade Biosciences"),
    ("ARXS", "Arxis"),
    ("ALMS", "Alumis"),
    ("COAG", "Hemab Therapeutics Holdings"),
    ("INDP", "Indaptus Therapeutics"),
    ("SFNC", "Simmons First National"),
    ("ATEX", "Anterix"),
    ("FFIN", "First Financial Bankshares"),
    ("EYE", "National Vision"),
    ("REYN", "Reynolds Consumer Products"),
    ("TRAX", "First Tracks Biotherapeutics"),
    ("IRON", "Disc Medicine"),
    ("ACLS", "Axcelis Technologies"),
    ("NEXT", "NextDecade"),
    ("FDMT", "4D Molecular Therapeutics"),
    ("IPAR", "依特香水"),
    ("CRSR", "Corsair Gaming"),
    ("BWMN", "Bowman Consulting"),
    ("PLMR", "Palomar Holdings"),
    ("ADMA", "ADMA Biologics"),
    ("ANAB", "AnaptysBio"),
    ("SERV", "Serve Robotics"),
    ("IEP", "伊坎企业"),
    ("LBTYA", "自由全球-A"),
    ("CABA", "Cabaletta Bio"),
    ("SCTX", "Scribe Therapeutics"),
    ("VELO", "Velo3D"),
    ("VECO", "维易科精密仪器"),
    ("QCRH", "QCR Holdings"),
    ("CERT", "Certara"),
    ("GCT", "大健云仓"),
    ("RUM", "RUM Group"),
    ("FFBC", "第一金融银行"),
    ("CBC", "Central Bancompany"),
    ("AMSC", "美国超导"),
    ("BABA", "阿里巴巴"),
    ("TSM", "台积电"),
    ("LLY", "礼来"),
    ("ORCL", "甲骨文"),
    ("JPM", "摩根大通"),
    ("GS", "高盛"),
    ("V", "Visa"),
    ("MRK", "默沙东"),
    ("XOM", "埃克森美孚"),
    ("CRCL", "Circle"),
    ("BRK.B", "伯克希尔-B"),
    ("FCX", "麦克莫兰铜金"),
    ("BAC", "美国银行"),
    ("CAT", "卡特彼勒"),
    ("CRM", "赛富时"),
    ("UNH", "联合健康"),
    ("BE", "Bloom Energy"),
    ("BSX", "波士顿科学"),
    ("COHR", "Coherent"),
    ("JNJ", "强生"),
    ("GEV", "GE Vernova"),
    ("DELL", "戴尔科技"),
    ("NOW", "ServiceNow"),
    ("DE", "迪尔股份"),
    ("ANET", "Arista Networks"),
    ("CVX", "雪佛龙"),
    ("C", "花旗集团"),
    ("KO", "可口可乐"),
    ("PG", "宝洁"),
    ("NEM", "纽曼矿业"),
    ("ABBV", "艾伯维公司"),
    ("TJX", "TJX公司"),
    ("MCK", "麦克森"),
    ("BMNR", "Bitmine Immersion Technologies"),
    ("BA", "波音"),
    ("MA", "万事达"),
    ("GE", "GE航天航空"),
    ("AEM", "伊格尔矿业"),
    ("COP", "康菲石油"),
    ("ABT", "雅培"),
    ("HD", "家得宝"),
    ("SNOW", "Snowflake"),
    ("WFC", "富国银行"),
    ("PFE", "辉瑞"),
    ("SYK", "史赛克"),
    ("DHR", "丹纳赫"),
    ("MCD", "麦当劳"),
    ("TGT", "塔吉特"),
    ("RTX", "雷神技术"),
    ("UBER", "优步"),
    ("NEE", "新纪元能源"),
    ("APH", "安费诺"),
    ("TMO", "赛默飞世尔"),
    ("MS", "摩根士丹利"),
    ("NU", "Nu Holdings"),
    ("CDE", "科尔黛伦矿业"),
    ("GLW", "康宁"),
    ("IBM", "IBM Corp"),
    ("ACN", "埃森哲"),
    ("HCA", "HCA医疗"),
    ("AXP", "美国运通"),
    ("CVNA", "Carvana"),
    ("IONQ", "IonQ Inc"),
    ("NET", "Cloudflare"),
    ("PATH", "UiPath"),
    ("VRT", "Vertiv Holdings"),
    ("UNP", "联合太平洋"),
    ("MPC", "马拉松原油"),
    ("SPOT", "Spotify Technology"),
    ("COF", "第一资本信贷"),
    ("SPGI", "标普全球"),
    ("PWR", "广达服务"),
    ("SCHW", "嘉信理财"),
    ("PM", "菲利普莫里斯"),
    ("T", "AT&T"),
    ("PAAS", "泛美白银"),
    ("AZO", "汽车地带"),
    ("WELL", "Welltower"),
    ("VZ", "Verizon"),
    ("AU", "AngloGold Ashanti"),
    ("CMG", "奇波雷墨西哥烧烤"),
    ("DIS", "迪士尼"),
    ("ETN", "伊顿"),
    ("VST", "Vistra Energy"),
    ("RDDT", "Reddit"),
    ("MDT", "美敦力"),
    ("ECL", "艺康集团"),
    ("CB", "安达保险"),
    ("VLO", "瓦莱罗能源"),
    ("NUE", "纽柯钢铁"),
    ("F", "福特汽车"),
    ("PSX", "Phillips 66"),
    ("TDG", "TransDigm"),
    ("LOW", "劳氏"),
    ("HL", "赫克拉矿业"),
    ("LMT", "洛克希德马丁"),
    ("MSI", "摩托罗拉解决方案"),
    ("MO", "奥驰亚"),
    ("FIX", "美国舒适系统"),
    ("ALL", "好事达"),
    ("EL", "雅诗兰黛"),
    ("TRGP", "Targa Resources"),
    ("TEL", "泰科电子"),
    ("NOK", "诺基亚"),
    ("NKE", "耐克"),
    ("SO", "美国南方公司"),
    ("ICE", "洲际交易所"),
    ("TRV", "旅行者财产险集团"),
    ("SHW", "宣伟公司"),
    ("DUK", "杜克能源"),
    ("FDX", "联邦快递"),
    ("CI", "信诺"),
    ("YUM", "Yum! Brands"),
    ("PNC", "PNC金融服务集团"),
    ("HLT", "希尔顿酒店"),
    ("B", "Barrick Mining"),
    ("XYZ", "Block"),
    ("PH", "派克汉尼汾"),
    ("CMI", "康明斯"),
    ("WMB", "威廉姆斯"),
    ("FN", "Fabrinet"),
    ("LHX", "L3Harris Technologies"),
    ("AZN", "阿斯利康"),
    ("VIK", "Viking Holdings"),
    ("HWM", "Howmet Aerospace"),
    ("CVS", "西维斯健康"),
    ("WPM", "Wheaton Precious Metals"),
    ("URI", "联合租赁"),
    ("NOC", "诺斯罗普格鲁曼"),
    ("NVO", "诺和诺德"),
    ("MTD", "梅特勒-托利多"),
    ("CF", "CF工业控股"),
    ("IR", "英格索兰"),
    ("MP", "MP Materials"),
    ("CLS", "天弘科技"),
    ("HIMS", "Hims & Hers Health"),
    ("MRSH", "达信"),
    ("CIEN", "Ciena"),
    ("BDX", "碧迪医疗"),
    ("DAR", "美国达尔令国际"),
    ("EOG", "EOG能源"),
    ("VMRK", "Vivmark Residential"),
    ("ALB", "美国雅保"),
    ("PCG", "太平洋煤电"),
    ("JCI", "江森自控"),
    ("MMM", "3M"),
    ("GM", "通用汽车"),
    ("BMY", "施贵宝"),
    ("MET", "大都会人寿"),
    ("PLD", "安博"),
    ("DVN", "戴文能源"),
    ("TPR", "Tapestry"),
    ("BLK", "贝莱德"),
    ("CCL", "嘉年华邮轮"),
    ("HUM", "哈门那"),
    ("A", "安捷伦科技"),
    ("RCL", "皇家加勒比邮轮"),
    ("SRE", "桑普拉能源"),
    ("BX", "黑石"),
    ("HPE", "慧与科技"),
    ("KGC", "金罗斯黄金"),
    ("DAL", "达美航空"),
    ("CW", "寇蒂斯莱特"),
    ("PGR", "前进保险"),
    ("APD", "Air Products & Chemicals"),
    ("WM", "美国废物管理"),
    ("DKS", "迪克体育用品"),
    ("SE", "Sea"),
    ("BP", "英国石油"),
    ("VALE", "淡水河谷"),
    ("RMD", "瑞思迈"),
    ("MOD", "摩丁制造"),
    ("CCJ", "Cameco"),
    ("BJ", "BJ批发俱乐部"),
    ("OXY", "西方石油"),
    ("BNY", "纽约梅隆银行"),
    ("USB", "美国合众银行"),
    ("SCCO", "南方铜业"),
    ("ZTS", "Zoetis"),
    ("GPN", "环汇有限公司"),
    ("SYF", "Synchrony Financial"),
    ("HIG", "哈特福德金融"),
    ("SLB", "斯伦贝谢"),
    ("CTVA", "Corteva"),
    ("KEYS", "Keysight Technologies"),
    ("RBLX", "Roblox"),
    ("TT", "Trane技术"),
    ("UPS", "联合包裹"),
    ("KMI", "金德尔摩根"),
    ("BHP", "必和必拓"),
    ("MCO", "穆迪"),
    ("LNG", "Cheniere Energy"),
    ("U", "Unity Software"),
    ("SMR", "NuScale Power"),
    ("RIO", "力拓"),
    ("SAP", "SAP SE"),
    ("FICO", "Fair Isaac"),
    ("FITB", "五三银行"),
    ("TWLO", "Twilio"),
    ("KR", "克罗格"),
    ("IQV", "艾昆纬"),
    ("TECK", "泰克资源有限公司"),
    ("PBR", "巴西石油公司"),
    ("WAT", "沃特世"),
    ("CL", "高露洁"),
    ("MTZ", "MasTec"),
    ("MOS", "美国美盛"),
    ("EQT", "EQT能源"),
    ("NRG", "NRG Energy"),
    ("RKT", "Rocket"),
    ("EMR", "艾默生电气"),
    ("SHEL", "壳牌"),
    ("ADM", "Archer Daniels Midland"),
    ("CAH", "卡地纳健康"),
    ("AMP", "阿莫斯莱斯金融"),
    ("RY", "加拿大皇家银行"),
    ("ATI", "ATI Inc"),
    ("DLR", "数字房地产信托公司"),
    ("TFC", "Truist Financial"),
    ("WEC", "威州能源"),
    ("WAB", "美国西屋制动"),
    ("HAL", "哈里伯顿"),
    ("ELV", "Elevance Health"),
    ("AME", "阿美特克"),
    ("DGX", "奎斯特诊疗"),
    ("AMT", "美国电塔"),
    ("CARR", "开利全球"),
    ("GWW", "美国固安捷"),
    ("CNP", "中点能源"),
    ("CFG", "Citizens Financial"),
    ("CRS", "卡朋特科技"),
    ("AJG", "亚瑟加拉格尔"),
    ("HPQ", "惠普"),
    ("RJF", "瑞杰金融"),
    ("DOW", "陶氏化学"),
    ("CRH", "CRH水泥"),
    ("FNV", "Franco-Nevada"),
    ("STT", "道富银行"),
    ("MLM", "马丁-玛丽埃塔材料"),
    ("APO", "阿波罗全球管理"),
    ("DOCN", "DigitalOcean"),
    ("GD", "通用动力"),
    ("FIG", "Figma Inc"),
    ("OKE", "欧尼克(万欧卡)"),
    ("KKR", "KKR & Co"),
    ("LYV", "Live Nation Entertainment"),
    ("NSC", "诺福克南方"),
    ("COR", "Cencora"),
    ("TOST", "Toast"),
    ("RVTY", "Revvity"),
    ("EIX", "爱迪生国际"),
    ("P", "Everpure"),
    ("VICI", "VICI Properties"),
    ("DINO", "HF Sinclair"),
    ("CNH", "凯斯纽"),
    ("OTIS", "奥的斯"),
    ("OKLO", "Oklo Inc"),
    ("TSN", "泰森食品"),
    ("SAN", "桑坦德银行"),
    ("DHI", "霍顿房屋"),
    ("AG", "First Majestic Silver"),
    ("BURL", "伯灵顿百货"),
    ("VEEV", "Veeva Systems"),
    ("AGI", "Alamos Gold"),
    ("FIS", "繁德信息技术"),
    ("PRU", "保德信金融"),
    ("LH", "徕博科"),
    ("AON", "怡安保险"),
    ("AWK", "美国水务"),
    ("RS", "Reliance"),
    ("CRL", "查尔斯河实验室"),
    ("AS", "亚玛芬体育"),
    ("D", "道明尼资源"),
    ("KVUE", "Kenvue"),
    ("STZ", "星座品牌"),
    ("O", "Realty Income"),
    ("VTR", "芬塔公司"),
    ("CMS", "CMS能源"),
    ("PCOR", "Procore Technologies"),
    ("EME", "EMCOR Group"),
    ("EW", "爱德华生命科学"),
    ("KEY", "KeyCorp"),
    ("VMC", "火神材料"),
    ("MSCI", "MSCI Inc"),
    ("ED", "爱迪生联合电气"),
    ("AA", "美国铝业公司"),
    ("ITW", "伊利诺伊机械"),
    ("UI", "厄比奎蒂"),
    ("WCC", "西科国际"),
    ("ROK", "罗克韦尔自动化"),
    ("DT", "Dynatrace"),
    ("NCLH", "挪威邮轮"),
    ("DK", "Delek US"),
    ("AIG", "美国国际集团"),
    ("STM", "意法半导体"),
    ("FERG", "Ferguson"),
    ("IEX", "IDEX Corp"),
    ("RSG", "共和废品处理"),
    ("JBL", "捷普科技"),
    ("AMRZ", "Amrize"),
    ("KNX", "Knight-Swift Transportation"),
    ("ONTO", "Onto Innovation"),
    ("GFI", "金田"),
    ("NI", "印北瓦电"),
    ("AFL", "美国家庭寿险"),
    ("MTB", "美国制商银行"),
    ("JOBY", "Joby Aviation"),
    ("NVT", "nVent Electric"),
    ("TDY", "Teledyne Technologies"),
    ("CLX", "高乐氏"),
    ("THC", "泰尼特"),
    ("NTR", "Nutrien"),
    ("SPG", "西蒙地产"),
    ("HUBS", "HubSpot"),
    ("EFX", "艾可菲"),
    ("Q", "Qnity Electronics"),
    ("ETR", "安特吉"),
    ("BBY", "百思买"),
    ("MFC", "宏利金融"),
    ("CLF", "克利夫兰克里夫"),
    ("DG", "美国达乐公司"),
    ("QSR", "餐饮品牌国际"),
    ("BG", "邦吉"),
    ("PPL", "宾州电力"),
    ("PBF", "PBF Energy"),
    ("ET", "Energy Transfer"),
    ("BEN", "Franklin Templeton"),
    ("RF", "地区金融"),
    ("PR", "Permian Resources"),
    ("INFQ", "Infleqtion"),
    ("RBRK", "Rubrik"),
    ("WSM", "Williams-Sonoma"),
    ("GWRE", "Guidewire Software"),
    ("EPAM", "EPAM Systems"),
    ("ACHR", "Archer Aviation"),
    ("DECK", "Deckers Outdoor"),
    ("GRMN", "佳明"),
    ("BR", "Broadridge金融解决方案"),
    ("IT", "加特纳"),
    ("OVV", "Ovintiv"),
    ("GIS", "通用磨坊"),
    ("FE", "第一能源"),
    ("AMX", "美洲移动"),
    ("CNC", "康西哥"),
    ("VIRT", "Virtu金融"),
    ("ARES", "Ares Management"),
    ("CNQ", "加拿大自然资源"),
    ("RPM", "RPM International"),
    ("BTI", "英美烟草"),
    ("RL", "拉夫劳伦"),
    ("EGO", "埃氏金业"),
    ("VLTO", "Veralto Corp"),
    ("G", "简伯特"),
    ("HUBB", "哈勃集团"),
    ("W", "Wayfair"),
    ("AAP", "Advance Auto Parts"),
    ("LYB", "利安德巴塞尔"),
    ("RACE", "法拉利"),
    ("INFY", "印孚瑟斯"),
    ("AER", "AerCap飞机租赁"),
    ("TYL", "泰勒科技"),
    ("NVS", "诺华制药"),
    ("SW", "Smurfit WestRock"),
    ("CSL", "卡莱尔伙伴"),
    ("SN", "SharkNinja"),
    ("SYY", "西思科公司"),
    ("ENB", "恩桥"),
    ("NVR", "NVR Inc"),
    ("SUNB", "Sunbelt Rentals Holdings"),
    ("WST", "West Pharmaceutical Services"),
    ("ATO", "Atmos Energy"),
    ("HDB", "HDFC银行"),
    ("SJM", "斯马克"),
    ("CPNG", "Coupang"),
    ("ITUB", "Itaú巴西联合银行"),
    ("LEN", "莱纳建筑"),
    ("RBA", "里奇兄弟拍卖"),
    ("SGI", "泰浦陛迪国际公司"),
    ("RIG", "Transocean"),
    ("FTI", "德希尼布FMC"),
    ("ETSY", "Etsy Inc"),
    ("PSA", "公共存储公司"),
    ("HSY", "好时"),
    ("PEG", "公务集团"),
    ("CP", "加拿大太平洋铁路"),
    ("LII", "雷诺士"),
    ("HBM", "Hudbay Minerals"),
    ("QXO", "QXO Inc"),
    ("AEE", "阿曼瑞恩"),
    ("OSCR", "Oscar Health"),
    ("UL", "联合利华(英国)"),
    ("USFD", "美国食品控股"),
    ("DRI", "达登饭店"),
    ("AIZ", "安信龙保险"),
    ("GPC", "Genuine Parts"),
    ("CCI", "冠城国际"),
    ("SEI", "Solaris Energy Infrastructure"),
    ("XYL", "赛莱默"),
    ("SNAP", "Snap Inc"),
    ("ARMK", "Aramark"),
    ("XPO", "XPO"),
    ("CAG", "康尼格拉"),
    ("VG", "Venture Global"),
    ("EXPD", "康捷国际物流"),
    ("APTV", "Aptiv PLC"),
    ("EAT", "布林克国际"),
    ("CHWY", "Chewy"),
    ("DY", "戴康工业"),
    ("TEVA", "梯瓦制药"),
    ("MUSA", "Murphy USA"),
    ("PFGC", "Performance Food"),
    ("SUI", "Sun Communities"),
    ("PINS", "Pinterest"),
    ("LUV", "西南航空"),
    ("CHD", "丘奇&德怀特"),
    ("ARE", "亚历山大房地产"),
    ("FLR", "福陆"),
    ("AES", "AES发电"),
    ("JHX", "詹姆斯哈迪"),
    ("CBRE", "世邦魏理仕"),
    ("PNR", "滨特尔"),
    ("ONON", "昂跑"),
    ("ZETA", "Zeta Global"),
    ("TD", "多伦多道明银行"),
    ("OMC", "宏盟集团"),
    ("DD", "杜邦"),
    ("PNW", "西帕纳卡资本"),
    ("GNRC", "Generac"),
    ("DTE", "DTE能源"),
    ("LVS", "金沙集团"),
    ("M", "梅西百货"),
    ("PAYC", "Paycom Software"),
    ("ALLE", "Allegion"),
    ("MOH", "Molina Healthcare"),
    ("TXT", "德事隆"),
    ("GDDY", "GoDaddy"),
    ("RNR", "RenaissanceRe Holdings"),
    ("SWK", "美国史丹利公司"),
    ("CAVA", "CAVA Group"),
    ("ITT", "ITT Inc"),
    ("FDS", "慧甚"),
    ("ERO", "Ero Copper"),
    ("DTM", "DT Midstream"),
    ("WCN", "Waste Connections"),
    ("AMCR", "Amcor"),
    ("ALSN", "艾里逊变速箱"),
    ("ES", "Eversource Energy"),
    ("BIRK", "勃肯"),
    ("HII", "亨廷顿英格尔斯工业"),
    ("TRP", "TC Energy"),
    ("MKC", "味好美"),
    ("ELF", "e.l.f. Beauty"),
    ("QGEN", "快而精医药"),
    ("CM", "加拿大帝国商业银行"),
    ("NLY", "Annaly Capital Management"),
    ("WRB", "WR柏克利"),
    ("TRU", "TransUnion"),
    ("APG", "APi Group"),
    ("SU", "森科能源"),
    ("ASX", "日月光半导体"),
    ("BWXT", "BWX Technologies"),
    ("EXK", "Endeavour Silver"),
    ("RBC", "RBC轴承"),
    ("EVR", "Evercore"),
    ("BEKE", "贝壳"),
    ("TKO", "TKO Group Holdings"),
    ("CPAY", "Corpay"),
    ("DOV", "都福集团"),
    ("MKL", "Markel Group"),
    ("ROL", "Rollins"),
    ("RDW", "Redwire"),
    ("SQM", "智利矿业化工"),
    ("KGS", "Kodiak Gas Services"),
    ("GGG", "固瑞克"),
    ("CNI", "加拿大国家铁路"),
    ("WSO", "华斯科"),
    ("BWA", "博格华纳"),
    ("LDOS", "Leidos"),
    ("UMC", "联电"),
    ("CPT", "卡姆登物业信托"),
    ("RH", "RH"),
    ("BMO", "蒙特利尔银行"),
    ("BVN", "布埃纳文图拉开采"),
    ("J", "雅各布工程"),
    ("AGX", "Argan"),
    ("CVE", "Cenovus能源"),
    ("AR", "Antero Resources"),
    ("BILL", "BILL Holdings"),
    ("BIO", "Bio-Rad实验室"),
    ("WHR", "惠而浦"),
    ("RRX", "Regal Rexnord"),
    ("IP", "国际纸业"),
    ("IAG", "Iamgold"),
    ("OC", "欧文斯科宁"),
    ("PHM", "普得集团"),
    ("BROS", "Dutch Bros"),
    ("TPL", "Texas Pacific Land"),
    ("GSK", "葛兰素史克"),
    ("STLA", "Stellantis NV"),
    ("HEI", "海科航空"),
    ("HNGE", "Hinge Health"),
    ("MHK", "莫霍克工业公司"),
    ("IOT", "Samsara"),
    ("DOC", "Healthpeak Properties"),
    ("NYT", "纽约时报"),
    ("ESTC", "Elastic"),
    ("HMY", "哈莫尼黄金"),
    ("OSK", "Oshkosh"),
    ("UDR", "UDR不动产信托"),
    ("UHS", "Universal Health Services"),
    ("FLUT", "Flutter Entertainment"),
    ("SPHR", "Sphere Entertainment"),
    ("SF", "Stifel Financial"),
    ("ITGR", "Integer Holdings"),
    ("PKG", "美国包装公司"),
    ("ZBH", "齐默巴奥米特控股"),
    ("EPD", "Enterprise Products"),
    ("FBIN", "Fortune Brands Innovations"),
    ("KLAR", "Klarna Group"),
    ("CNK", "喜满客影城"),
    ("XPEV", "小鹏集团"),
    ("BRK.A", "伯克希尔-A"),
    ("BAX", "百特国际"),
    ("PPG", "PPG工业"),
    ("BN", "Brookfield"),
    ("BLDR", "Builders FirstSource"),
    ("NIO", "蔚来"),
    ("ARW", "艾睿"),
    ("ELAN", "Elanco Animal Health"),
    ("CTRE", "CareTrust REIT"),
    ("OHI", "Omega Healthcare Investors"),
    ("AGCO", "爱科集团"),
    ("ACM", "AECOM Technology"),
    ("GAP", "Gap Inc"),
    ("BXP", "BXP Inc"),
    ("SNA", "实耐宝"),
    ("SM", "SM Energy"),
    ("TOL", "托尔兄弟"),
    ("AHR", "American Healthcare REIT"),
    ("BNS", "丰业银行"),
    ("DVA", "德维特"),
    ("FLO", "花苑食品"),
    ("SNX", "新聚思"),
    ("ANF", "爱芬奇"),
    ("MT", "安赛乐米塔尔"),
    ("ESI", "Element Solutions"),
    ("BUD", "百威英博"),
    ("BBWI", "Bath & Body Works"),
    ("RNG", "RingCentral"),
    ("AMR", "Alpha Metallurgical"),
    ("CX", "西麦斯"),
    ("ALLY", "Ally Financial"),
    ("SBSW", "Sibanye Stillwater"),
    ("ALK", "阿拉斯加航空"),
    ("JXN", "Jackson Financial"),
    ("ARX", "Accelerant Holdings"),
    ("S", "SentinelOne"),
    ("FTV", "Fortive"),
    ("RHI", "罗致恒富"),
    ("MAA", "MAA房产信托"),
    ("H", "凯悦酒店"),
    ("STE", "思泰瑞医疗"),
    ("CACI", "CACI国际"),
    ("HLI", "华利安"),
    ("WOLF", "Wolfspeed"),
    ("PBR.A", "巴西石油公司-Prefer"),
    ("UGI", "UGI公用事业"),
    ("IRM", "铁山"),
    ("HXL", "赫氏"),
    ("FHN", "第一地平线国家银行"),
    ("KMX", "车美仕"),
    ("SKM", "韩国SK电信"),
    ("CLH", "Clean Harbors"),
    ("DHT", "DHT控股"),
    ("MPLX", "MPLX LP"),
    ("JLL", "仲量联行"),
    ("AMG", "Affiliated Managers"),
    ("LNC", "林肯国民"),
    ("IVZ", "景顺"),
    ("FDXF", "FEDEX FREIGHT HOLDING CO INC"),
    ("DEO", "帝亚吉欧"),
    ("VAL", "华仕伯"),
    ("WAL", "阿莱恩斯西部银行"),
    ("MTDR", "Matador Resources"),
    ("NOG", "Northern Oil & Gas"),
    ("GME", "游戏驿站"),
    ("RRC", "山脉资源"),
    ("ACA", "Arcosa"),
    ("BRO", "Brown & Brown"),
    ("FPS", "Forgent Power Solutions"),
    ("MTN", "Vail Resorts"),
    ("EXR", "Extra Space Storage"),
    ("BOOT", "Boot Barn Holdings"),
    ("OWL", "Blue Owl Capital"),
    ("CMC", "美国工商五金公司"),
    ("FND", "Floor & Decor"),
    ("TME", "腾讯音乐"),
    ("SA", "Seabridge Gold"),
    ("FOUR", "Shift4 Payments"),
    ("PLNT", "Planet Fitness"),
    ("IBN", "印度工业信贷投资银行"),
    ("IFF", "国际香料香精"),
    ("R", "莱德系统"),
    ("REXR", "Rexford Industrial Realty"),
    ("VSXY", "维多利亚的秘密"),
    ("UNM", "尤纳姆集团"),
    ("EQH", "Equitable"),
    ("GEO", "GEO惩教集团"),
    ("VFC", "威富集团"),
    ("MLI", "木勒工业"),
    ("BAM", "布鲁克菲尔德资产管理"),
    ("GL", "Globe Life"),
    ("MGY", "Magnolia Oil & Gas"),
    ("CFR", "库伦佛寺银行"),
    ("ENS", "艾诺斯"),
    ("SONY", "索尼"),
    ("TFX", "泰利福"),
    ("BALL", "鲍尔包装"),
    ("AVY", "艾利丹尼森"),
    ("TTE", "道达尔"),
    ("WY", "惠好"),
    ("NEU", "NewMarket"),
    ("FSM", "Fortuna Silver Mines"),
    ("AVTR", "Avantor"),
    ("MAS", "马斯科"),
    ("HRB", "H&R布洛克税务"),
    ("PL", "Planet Labs PBC"),
    ("KRMN", "Karman Holdings"),
    ("CRBG", "Corebridge Financial"),
    ("MGM", "美高梅"),
    ("FRO", "Frontline"),
    ("WEX", "WEX Inc"),
    ("LEU", "Centrus Energy"),
    ("HRL", "荷美尔食品"),
    ("ENVA", "易诺华"),
    ("EG", "Everest Group"),
    ("JBTM", "约翰宾技术"),
    ("HCC", "Warrior Met Coal"),
    ("VOYA", "Voya金融"),
    ("EHC", "Encompass Health"),
    ("YETI", "YETI Holdings"),
    ("EXP", "Eagle Materials"),
    ("CXW", "美国惩教公司"),
    ("SOLV", "Solventum"),
    ("EQNR", "Equinor"),
    ("COMP", "Compass"),
    ("GKOS", "Glaukos"),
    ("MOG.A", "Moog-A"),
    ("VIST", "Vista Energy"),
    ("HLN", "Haleon"),
    ("GMED", "Globus Medical"),
    ("PAG", "潘世奇汽车"),
    ("RYN", "雷欧尼尔"),
    ("TE", "T1 Energy"),
    ("ACI", "艾伯森"),
    ("EGP", "EastGroup Properties"),
    ("NOV", "华高"),
    ("STAG", "STAG Industrial"),
    ("YMM", "满帮"),
    ("VAC", "万豪度假环球"),
    ("HSBC", "汇丰控股"),
    ("BBD", "布拉德斯科银行-Preferred"),
    ("TKR", "铁姆肯"),
    ("BA.PRA", "BOEING CO 6% DEP SHS RE 1/20TH PFD MAN CNV SR A"),
    ("RELX", "RELX PLC"),
    ("MSGS", "麦迪逊运动"),
    ("MSM", "MSC Industrial Direct"),
    ("SPXC", "SPX Technologies"),
    ("DDS", "迪拉德百货"),
    ("LTH", "Life Time"),
    ("ELS", "宜居生活资产信托"),
    ("NXE", "NexGen Energy"),
    ("MGA", "曼格纳国际"),
    ("CRGY", "Crescent Energy"),
    ("ESS", "埃塞克斯信托"),
    ("L", "洛斯公司"),
    ("TAP", "莫库酒业"),
    ("BLSH", "Bullish"),
    ("FCN", "FTI咨询"),
    ("TXNM", "TXNM Energy"),
    ("ALC", "Alcon"),
    ("TM", "丰田汽车"),
    ("BAP", "Credicorp"),
    ("PRIM", "Primoris Services"),
    ("AIT", "应用工业技术"),
    ("AOS", "A.O.史密斯"),
    ("ABEV", "Ambev SA"),
    ("JBS", "JBS N.V"),
    ("FNF", "富达国民金融"),
    ("PRMB", "Primo Brands"),
    ("BAH", "博思艾伦咨询公司"),
    ("VSH", "威世科技"),
    ("KVYO", "Klaviyo"),
    ("POST", "Post Holdings"),
    ("PNFP", "Pinnacle Financial Partners"),
    ("AI", "C3.ai"),
    ("CVI", "CVR能源"),
    ("TEX", "特雷克斯"),
    ("PARR", "Par Pacific"),
    ("ESAB", "ESAB Corp"),
    ("WTS", "沃茨水工业"),
    ("BKD", "布鲁克代尔高级护理"),
    ("BTE", "Baytex Energy"),
    ("WH", "Wyndham Hotels & Resorts"),
    ("INVH", "Invitation Homes"),
    ("KNTK", "Kinetik Holdings"),
    ("TTC", "托罗配件"),
    ("DOCS", "Doximity"),
    ("PSN", "Parsons"),
    ("FLS", "福斯"),
    ("ZIM", "以星航运"),
    ("KIM", "金科"),
    ("SHAK", "Shake Shack"),
    ("BYD", "博伊德赌场"),
    ("EMBJ", "巴西航空工业"),
    ("ECG", "Everus Construction"),
    ("AMTM", "Amentum Holdings"),
    ("AROC", "Archrock"),
    ("ALV", "奥托立夫"),
    ("ORA", "奥玛特科技"),
    ("VPG", "Vishay精密集团"),
    ("TDW", "潮水公司"),
    ("PBA", "Pembina Pipeline"),
    ("CUBE", "CubeSmart"),
    ("SARO", "StandardAero"),
    ("BCS", "巴克莱银行"),
    ("RSI", "Rush Street Interactive"),
    ("BBAI", "BigBear.ai Holdings"),
    ("ATEN", "A10 Networks"),
    ("BF.B", "百富门-B"),
    ("RGA", "美国再保险集团"),
    ("FRT", "FRT信托"),
    ("CHE", "Chemed"),
    ("HAE", "美国血液技术"),
    ("SITE", "SiteOne Landscape Supply"),
    ("VNO", "沃那多房信"),
    ("WPC", "W.P. Carey"),
    ("AIR", "AAR Corp"),
    ("CRC", "加州资源"),
    ("JEF", "杰富瑞"),
    ("SSB", "SouthState Bank"),
    ("NE", "Noble"),
    ("WTM", "白山保险集团"),
    ("LMND", "Lemonade"),
    ("GPI", "汽车一组"),
    ("SBS", "Sabesp"),
    ("CR", "Crane"),
    ("UBS", "瑞银"),
    ("DX", "德尼克斯投资"),
    ("GXO", "GXO Logistics"),
    ("MIR", "Mirion"),
    ("ESE", "ESCO科技"),
    ("ALH", "Alliance Laundry Holdings"),
    ("AWI", "阿姆斯特朗工业"),
    ("CCK", "皇冠控股"),
    ("HOG", "哈雷戴维森"),
    ("KSS", "柯尔百货"),
    ("CNM", "Core & Main"),
    ("WLK", "Westlake"),
    ("EMN", "伊士曼化工"),
    ("PAY", "Paymentus Holdings"),
    ("LPX", "Louisiana-Pacific"),
    ("TBBB", "BBB Foods"),
    ("LYG", "劳埃德"),
    ("TU", "泰勒斯"),
    ("DLB", "杜比实验室"),
    ("IDA", "Idacorp"),
    ("MBGL", "Mobility Global"),
    ("STNG", "Scorpio Tankers"),
    ("LW", "Lamb Weston"),
    ("BTU", "Peabody Energy"),
    ("WTRG", "Essential Utilities"),
    ("SXT", "Sensient Technologies"),
    ("VOYG", "Voyager Technologies"),
    ("OGS", "ONE Gas"),
    ("MTRN", "Materion"),
    ("MAC", "马塞里奇房产"),
    ("MAN", "万宝盛华"),
    ("IBP", "Installed Building Products"),
    ("SOC", "Sable Offshore"),
    ("KD", "Kyndryl"),
    ("AN", "车之国公司"),
    ("YOU", "Clear Secure"),
    ("SKY", "Champion Homes"),
    ("MTG", "MGIC Investment"),
    ("OR", "Osisko Gold Royalties"),
    ("KNSL", "Kinsale Capital"),
    ("LEA", "李尔"),
    ("JMKE", "Jersey Mike’s Subs"),
    ("RHP", "Ryman Hospitality Properties"),
    ("BB", "黑莓"),
    ("PEN", "Penumbra"),
    ("CVSA", "Covista"),
    ("ADC", "美国同意房地产公司"),
    ("AM", "Antero Midstream"),
    ("NVST", "Envista Holdings"),
    ("PK", "Park Hotels & Resorts Inc"),
    ("HEI.A", "海科航空-A"),
    ("ATR", "AptarGroup"),
    ("BFLY", "Butterfly Network"),
    ("PVH", "PVH Corp"),
    ("MUR", "墨菲石油"),
    ("BKH", "黑山"),
    ("HESM", "Hess Midstream"),
    ("GPK", "Graphic Packaging"),
    ("AUB", "Atlantic Union Bankshares"),
    ("KRG", "凯特地产信托"),
    ("CNR", "Core Natural Resources"),
    ("OGE", "OGE Energy"),
    ("SIG", "西格内特珠宝"),
    ("WU", "西联汇款"),
    ("TX", "特尔尼翁钢铁"),
    ("LBRT", "Liberty Energy"),
    ("AXS", "埃克斯资本"),
    ("LAD", "利西亚车行"),
    ("KMT", "肯纳金属"),
    ("DBRG", "DigitalBridge Group"),
    ("OII", "国际海洋工程"),
    ("AEO", "美鹰服饰"),
    ("POR", "波特兰通用电气"),
    ("WMS", "Advanced Drainage"),
    ("NPO", "Enpro"),
    ("KTB", "Kontoor Brands"),
    ("HNI", "HNI Corp"),
    ("KKR.PRD", "KKR & CO INC 6.25% MAND CONV PREF SHARES SER D"),
    ("GIL", "吉登运动服"),
    ("ST", "Sensata Technologies"),
    ("CWEN", "Clearway Energy-C"),
    ("MC", "Moelis & Co"),
    ("FLG", "纽约社区银行"),
    ("FNB", "F.N.B. Corp"),
    ("APLE", "Apple Hospitality REIT"),
    ("CE", "塞拉尼斯"),
    ("DCI", "唐纳森"),
    ("SON", "Sonoco Products"),
    ("NJR", "新泽西能源"),
    ("OPLN", "Openlane"),
    ("STWD", "Starwood Property Trust"),
    ("RXO", "RXO Inc"),
    ("VVV", "胜牌"),
    ("FMX", "FEMSA"),
    ("PB", "Prosperity Bancshares"),
    ("CRI", "卡特"),
    ("CHH", "精选国际酒店"),
    ("INSW", "International Seaways"),
    ("CBZ", "CBIZ Inc"),
    ("AMH", "American Homes 4 Rent"),
    ("MATX", "Matson"),
    ("SCI", "Service Corporation International"),
    ("YUMC", "百胜中国"),
    ("NGG", "英国国家电网公司"),
    ("FTS", "Fortis"),
    ("MIAX", "迈阿密国际控股"),
    ("SMG", "The Scotts Miracle"),
    ("CUZ", "卡津斯不动产信托基金"),
    ("WK", "Workiva"),
    ("RITM", "Rithm Capital"),
    ("BW", "Babcock & Wilcox Enterprises"),
    ("GHC", "格雷厄姆控股"),
    ("TREX", "Trex Co."),
    ("ING", "荷兰国际集团"),
    ("BC", "宾士域"),
    ("PRI", "Primerica"),
    ("HRI", "Herc Holdings"),
    ("VMI", "维蒙特工业"),
    ("GBCI", "冰川万通金控"),
    ("TDS", "电话和数据系统"),
    ("CSTM", "Constellium"),
    ("BH", "Biglari Holdings"),
    ("THG", "汉诺威保险"),
    ("BOX", "Box Inc"),
    ("PJT", "PJT Partners"),
    ("PII", "北极星"),
    ("VGNT", "VERSIGENT PLC"),
    ("BFH", "Bread Financial"),
    ("AESI", "Atlas Energy Solutions"),
    ("ORI", "Old Republic International"),
    ("INGR", "宜瑞安"),
    ("TS", "泰纳瑞斯钢铁"),
    ("KBH", "KB Home"),
    ("WRBY", "Warby Parker"),
    ("LAZ", "Lazard"),
    ("DB", "德意志银行"),
    ("LUMN", "Lumen Technologies"),
    ("CGAU", "Centerra Gold"),
    ("BKV", "BKV Corp"),
    ("KBR", "KBR科技"),
    ("BDC", "百通公司"),
    ("KN", "Knowles"),
    ("UTI", "环球技术学院"),
    ("KOS", "Kosmos Energy"),
    ("BCO", "The Brink's"),
    ("CNO", "康塞科"),
    ("ABG", "阿斯伯里汽车"),
    ("QTWO", "Q2 Holdings"),
    ("ARIS", "Aris Mining"),
    ("GLOB", "Globant"),
    ("LPG", "Dorian LPG"),
    ("FIGS", "FIGS Inc"),
    ("TWO", "Two Harbors Investment"),
    ("HASI", "HA Sustainable Infrastructure"),
    ("GTES", "Gates Industrial"),
    ("UNF", "第一联合"),
    ("ATKR", "Atkore"),
    ("THO", "索尔工业"),
    ("DXYZ", "Destiny Tech100"),
    ("AYI", "Acuity"),
    ("BRX", "Brixmor Property Group"),
    ("GOLF", "高尔史密斯国际控股"),
    ("CPRI", "Capri Holdings"),
    ("SII", "Sprott"),
    ("NUVB", "Nuvation Bio"),
    ("TPC", "Tutor Perini"),
    ("SR", "Spire"),
    ("WT", "智慧树"),
    ("ASB", "Associated Banc"),
    ("TRNO", "Terreno Realty"),
    ("GPOR", "格尔夫波特能源"),
    ("REZI", "Resideo Technologies"),
    ("MUFG", "三菱日联金融"),
    ("TAL", "好未来"),
    ("BMI", "Badger Meter"),
    ("RAL", "Ralliant"),
    ("VNT", "Vontier"),
    ("LB", "LandBridge"),
    ("SAM", "波斯顿啤酒"),
    ("MANE", "Veradermics"),
    ("HP", "赫尔默里奇和佩恩材料"),
    ("GFL", "GFL Environmental"),
    ("FR", "第一工业地产"),
    ("BETA", "BETA Technologies"),
    ("GATX", "GATX Corp"),
    ("BBVA", "西班牙毕尔巴鄂银行"),
    ("AXTA", "艾仕得涂料系统"),
    ("UAA", "安德玛-A"),
    ("LAC", "Lithium Americas"),
    ("EROC", "ERock"),
    ("CNX", "康索尔能源"),
    ("NFG", "National Fuel Gas"),
    ("BMA", "Banco Macro"),
    ("BFAM", "Bright Horizons Family Solutions"),
    ("OLN", "欧林"),
    ("KAI", "凯登纸业"),
    ("TNK", "Teekay Tankers"),
    ("GGB", "盖尔道钢铁"),
    ("WHD", "Cactus"),
    ("ANDG", "Andersen Group"),
    ("TDC", "天睿公司"),
    ("CRK", "康斯托克能源"),
    ("SG", "Sweetgreen"),
    ("KNF", "Knife River"),
    ("ABCB", "ABC银行"),
    ("GNK", "根科船务贸易"),
    ("HR", "医疗保健房地产信托"),
    ("MAIR", "Madison Air Solutions Corp"),
    ("LOAR", "Loar Holdings"),
    ("STUB", "Stubhub Holdings"),
    ("NNN", "NNN REIT"),
    ("BCE", "加拿大贝尔"),
    ("BZH", "贝哲房屋"),
    ("CSW", "CSW Industrials"),
    ("KEX", "卡比海运"),
    ("OMF", "OneMain"),
    ("RLI", "RLI保险"),
    ("HGV", "Hilton Grand Vacations"),
    ("PRGO", "百利高"),
    ("HMC", "本田汽车"),
    ("AMPX", "Amprius Technologies"),
    ("HOMB", "Home BancShares"),
    ("AFG", "美国金融"),
    ("UAMY", "United States Antimony"),
    ("HOV", "霍夫纳尼安"),
    ("NWG", "NatWest"),
    ("EPRT", "Essential Properties Realty Trust, Inc."),
    ("AVA", "阿维斯塔"),
    ("UTZ", "Utz Brands"),
    ("AVNT", "Avient"),
    ("LEVI", "李维斯"),
    ("GEF", "格瑞夫"),
    ("RYAN", "Ryan Specialty Holdings"),
    ("VIPS", "唯品会"),
    ("ZTO", "中通快递"),
]
# name lookup
TICKER_NAMES = {t: n for t, n in WATCHLIST}

# ═══════════════════════════════════════════════════════════════════
#  INDICATOR CORE
# ═══════════════════════════════════════════════════════════════════

def calc_garypower(df):
    o, h, l, c, v = df["open"], df["high"], df["low"], df["close"], df["volume"]

    # 1. 基础价格与 PJJ 计算
    # PJJ:=DMA((H + L + C * 2) / 4, 0.9);
    pjj_input = (h + l + c * 2) / 4
    pjj = pjj_input.ewm(alpha=0.9, adjust=False).mean()

    # 2. EMA 计算
    def pine_ema(series, period):
        alpha = 2 / (period + 1)
        return series.ewm(alpha=alpha, adjust=False).mean()

    jj1 = pine_ema(pjj, 3)
    jj = jj1.shift(1)

    # 3. 流量控制算法 (XVL)
    # QJJ:=VOL / ((H - L) * 2 - ABS(C - O));
    denom = (h - l) * 2 - (c - o).abs()
    denom = denom.replace(0, np.nan)  # 规避分母为0导致的极值不稳定
    qjj = v / denom

    bull = c > o
    bear = c < o

    xvl1 = np.where(bull, qjj * (h - l), np.where(bear, qjj * (h - o + c - l), v / 2))
    xvl2 = np.where(bull, -(qjj * (h - c + o - l)), np.where(bear, -(qjj * (h - l)), -(v / 2)))
    xvl = xvl1 + xvl2

    hsl = pd.Series(xvl, index=df.index) / 20 / 1.15
    gp = hsl * 0.6  # 力度:HSL*0.6 完美对齐

    gjll = hsl * 0.55 + hsl.shift(1) * 0.33 + hsl.shift(2) * 0.22
    gs = pine_ema(gjll.fillna(0), 3)
    pw = gp / gs.abs()

    # 4. 力度新高:TOPRANGE(力度) -> 动态回溯算法
    src = gp.values
    n = len(src)
    days = np.zeros(n)
    
    for idx in range(1, n):
        val = src[idx]
        count = 0
        for j in range(idx - 1, -1, -1):
            if src[j] < val:
                count += 1
            else:
                break
        days[idx] = count

    days_series = pd.Series(days, index=df.index)

    # 5. 状态机逻辑及错位对齐
    bar_index = np.arange(n)
    since_last_gt100 = np.full(n, np.nan)
    last_gt100_bar = np.nan

    # 计算距离上次满足条件距今的天数
    for idx in range(n):
        if not np.isnan(days[idx]) and days[idx] > 100:
            last_gt100_bar = bar_index[idx]
        if not np.isnan(last_gt100_bar):
            since_last_gt100[idx] = bar_index[idx] - last_gt100_bar

    since_last_gt100_series = pd.Series(since_last_gt100, index=df.index)

    # 6. 条件判断：days > 400 并且【上一根】距上次>100天数 > 100，创400日新高，同时距离上次创100日新高的天数是100天
    condition_a = (days_series > 1000) & (since_last_gt100_series.shift(1) > 100)

    # 7. 组装输出
    out = df.copy()
    out["gp"] = gp
    out["gs"] = gs
    out["pw"] = pw
    out["days"] = days_series
    out["since_last_gt100"] = since_last_gt100_series
    out["conditionA"] = condition_a
    return out


# ═══════════════════════════════════════════════════════════════════
#  DATA FETCH (强力穿透与高精度版：确保拿到最新价，保留3位小数)
# ═══════════════════════════════════════════════════════════════════

def fetch_data(ticker, period="5y"):
    import yfinance as yf
    import pandas as pd
    import numpy as np
    
    t = yf.Ticker(ticker)
    
    # 1. 核心大招：利用 period="1mo" 的最高实时权限榨干 Yahoo 的最新“今天”数据
    # Yahoo 的服务器对 1mo/3mo 内的数据刷新率最高，能强制穿透未完全结算的最新交易日
    df_recent = t.history(period="1mo", interval="1d", auto_adjust=True, keepna=True)
    
    # 2. 如果最新数据里没有今天，或者你想双重保险，拉取 5y 的基础历史数据
    df_history = t.history(period=period, interval="1d", auto_adjust=True, keepna=True)
    
    # 3. 合并新旧账本，确保最新的一天（周五）绝对被囊括进来
    # combined 会自动根据日期 Index 去重并保留最新的那根 K 线
    raw = pd.concat([df_history, df_recent]).sort_index()
    raw = raw[~raw.index.duplicated(keep='last')]
    
    if raw.empty:
        raise ValueError(f"No data returned for {ticker}")
        
    # 兼容多级索引
    if isinstance(raw.columns, pd.MultiIndex):
        raw.columns = raw.columns.get_level_values(0)
        
    raw.columns = [c.lower() for c in raw.columns]
    
    # 4. 过滤成交量为 0 的日子（但如果是今天且正在交易，Volume 可能暂时为 NaN，要保留）
    # 只有当 Volume 明确存在且等于 0 的非交易日才过滤
    raw = raw[~(raw["volume"] == 0)]
    
    # 5. 关键修复：不要做任何 round() 强制截断！
    # 很多低价股/美股 ETF 报价在 3 位甚至 4 位小数，这里必须保持原始 float64 精度用于后面指标计算
    # 向前填充未结算数据（如果是盘中，防止 Close 暂时为 NaN）
    raw = raw.ffill()
    
    return raw[["open", "high", "low", "close", "volume"]].dropna()


# ═══════════════════════════════════════════════════════════════════
#  SCANNER
# ═══════════════════════════════════════════════════════════════════

def scan_ticker(ticker, period="5y"):
    try:
        df = fetch_data(ticker, period=period)
        out = calc_garypower(df)
        
        # 获取最后一根 K 线的数据
        last = out.iloc[-1]
        c = last["close"]
        gp_val = last["gp"]
        d = last["days"]
        s = last["since_last_gt100"]
        cond_a = last["conditionA"]
       
        # 打印触发状态 (已增加 Close 和 力度 并在控制台格式化对齐)
        # 找到这部分代码，修改控制台打印和 round 位数：
        status_str = "🔥【触发信号】" if cond_a else ""
        # 修复控制台打印：Close 改为 :>.3f 保留3位小数
        print(f": Close={c:>.3f}, 力度(gp)={gp_val:>.2f}, "
              f"Days={int(d) if not np.isnan(d) else 'NaN'}, "
              f"Since={out['since_last_gt100'].shift(1).iloc[-1]}  {status_str}")

        if cond_a:
           save_signal_to_kv(ticker, c, d, s)

        return {
            "ticker"          : ticker,
            "name"            : TICKER_NAMES.get(ticker, ""),
            "date"            : out.index[-1].strftime("%Y-%m-%d"),
            # 💡 核心修改：close 的四舍五入至少保留 4 位，或者干脆不 round 维持高精度
            "close"           : round(float(last["close"]), 4), 
            "gp"              : round(float(last["gp"]), 2),
            "gs"              : round(float(last["gs"]), 2),
            "pw"              : round(float(last["pw"]), 4),
            "days"            : int(d) if not np.isnan(d) else None,
            "since_last_gt100": int(s) if not np.isnan(s) else None,
            "conditionA"      : bool(cond_a),
            "error"           : None,
        }
    except Exception as e:
        return {
            "ticker": ticker, "name": TICKER_NAMES.get(ticker, ""),
            "date": None, "close": None, "gp": None, "gs": None,
            "pw": None, "days": None, "since_last_gt100": None,
            "conditionA": False, "error": str(e),
        }

def scan_all(period="5y"):
    tickers = [t for t, _ in WATCHLIST]
    total   = len(tickers)
    results = []
    for i, t in enumerate(tickers, 1):
        print(f"[{i:>{len(str(total))}}/{total}] {t:<11}", end=" ", flush=True)
        r = scan_ticker(t, period=period)
        results.append(r)

    df = pd.DataFrame(results)
    df = df.sort_values(["conditionA", "days"], ascending=[False, False])
    return df
    
# ═══════════════════════════════════════════════════════════════════
#  写入CLOUDFLARE KV
# ═══════════════════════════════════════════════════════════════════
# 1. 独立且安全的 KV 写入函数（完全独立，不影响原程序）
def save_signal_to_kv(ticker, close, days, since):
    try:
        # 获取环境变量
        account_id = os.environ.get("CLOUDFLARE_ACCOUNT_ID")
        namespace_id = os.environ.get("CLOUDFLARE_KV_NAMESPACE_ID")
        api_token = os.environ.get("CLOUDFLARE_API_TOKEN")
        
        if not all([account_id, namespace_id, api_token]):
            print(f"DEBUG - Missing Configs:")
            print(f"  Account ID: {bool(account_id)}")
            print(f"  Namespace ID: {bool(namespace_id)}")
            print(f"  API Token: {bool(api_token)}")
            return

        vancouver_tz = ZoneInfo("America/Vancouver")
        date_str = datetime.now(vancouver_tz).strftime("%Y-%m-%d")
        key = f"signals:{date_str}:{ticker}"
        
        record = {
            "date": date_str,
            "code": ticker,
            "price": float(close),
            "days": int(days),
            "since": int(since),
            "receivedAt": datetime.now().isoformat() + "Z",
            "source": "scanner"
        }
        
        url = f"https://api.cloudflare.com/client/v4/accounts/{account_id}/storage/kv/namespaces/{namespace_id}/values/{key}"
        requests.put(url, headers={"Authorization": f"Bearer {api_token}", "Content-Type": "application/json"}, json=record)
    except Exception as e:
        print(f"KV 写入跳过或失败: {e}")

# ═══════════════════════════════════════════════════════════════════
#  EMAIL  (Resend)
# ═══════════════════════════════════════════════════════════════════


RESEND_TO   = [
    "garyfocus@hotmail.com",
    "zhyld13@gmail.com",
]
RESEND_FROM = "AI-选股 <messenger@ceic.ca>"


def build_html(signals, scan_date, total_scanned, errors):
    """Build a clean HTML email body."""

    def signal_rows(rows):
        out = ""
        for r in rows:
            out += f"""
            <tr>
              <td style="padding:8px 12px;border-bottom:1px solid #2a2a2a;font-weight:600;color:#f0f0f0;">{r['ticker']}</td>
              <td style="padding:8px 12px;border-bottom:1px solid #2a2a2a;color:#aaa;">{r['name']}</td>
              <td style="padding:8px 12px;border-bottom:1px solid #2a2a2a;color:#f0f0f0;text-align:right;">{r['close']}</td>
              <td style="padding:8px 12px;border-bottom:1px solid #2a2a2a;color:#4ade80;text-align:right;">{r['days']}</td>
              <td style="padding:8px 12px;border-bottom:1px solid #2a2a2a;color:#60a5fa;text-align:right;">{r['since_last_gt100']}</td>
              <td style="padding:8px 12px;border-bottom:1px solid #2a2a2a;color:#fbbf24;text-align:right;">{round(r['pw'],3) if r['pw'] else '–'}</td>
            </tr>"""
        return out

    error_section = ""
    if errors:
        error_section = f"""
        <p style="margin-top:24px;color:#888;font-size:12px;">
          ⚠ {len(errors)} ticker(s) failed to load:
          {', '.join(e['ticker'] for e in errors)}
        </p>"""

    signal_count = len(signals)
    subject_note = f"{signal_count} signal(s)" if signal_count else "No signals"

    return f"""
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#0d0d0d;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
  <div style="max-width:680px;margin:32px auto;background:#141414;border-radius:12px;overflow:hidden;border:1px solid #222;">

    <div style="background:linear-gradient(135deg,#1a1a2e,#16213e);padding:28px 32px;">
      <div style="font-size:22px;font-weight:700;color:#e2e8f0;letter-spacing:1px;">
        📡 AI-选股
      </div>
      <div style="margin-top:6px;color:#64748b;font-size:13px;">
        {scan_date} &nbsp;·&nbsp; 
      </div>
    </div>

    <div style="padding:28px 32px;">
      {'<p style="color:#4ade80;font-size:15px;font-weight:600;margin-bottom:16px;">🔔 AI 选股结果</p>' if signals else '<p style="color:#888;font-size:15px;">今天没有符合条件的个股.</p>'}

      {'<table style="width:100%;border-collapse:collapse;font-size:13px;"><thead><tr style="background:#1e1e1e;"><th style="padding:8px 12px;text-align:left;color:#64748b;font-weight:500;">Ticker</th><th style="padding:8px 12px;text-align:left;color:#64748b;font-weight:500;">名称</th><th style="padding:8px 12px;text-align:right;color:#64748b;font-weight:500;">Close</th><th style="padding:8px 12px;text-align:right;color:#64748b;font-weight:500;">分数</th><th style="padding:8px 12px;text-align:right;color:#64748b;font-weight:500;">Since</th><th style="padding:8px 12px;text-align:right;color:#64748b;font-weight:500;">量能</th></tr></thead><tbody>' + signal_rows(signals) + '</tbody></table>' if signals else ''}

      {error_section}
    </div>

    <div style="padding:16px 32px;border-top:1px solid #1e1e1e;text-align:center;font-size:11px;color:#374151;">
      Gary AI 选股 · Automated by GitHub Actions
    </div>
  </div>
</body>
</html>
""", f"Gary AI 选股结果 {scan_date} | {subject_note}"


def send_email(api_key, html_body, subject):
    try:
        resp = requests.post(
            "https://api.resend.com/emails",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type" : "application/json",
                "User-Agent"   : "Mozilla/5.0 (compatible; GaryPOWER/1.0)",
            },
            json={
                "from"   : RESEND_FROM,
                "to"     : RESEND_TO,
                "subject": subject,
                "html"   : html_body,
            },
            timeout=20,
        )
        if resp.status_code in (200, 201):
            print(f"✅ Email sent  →  {RESEND_TO}  (status {resp.status_code})")
            return True
        else:
            print(f"❌ Resend error {resp.status_code}: {resp.text}")
            return False
    except Exception as e:
        print(f"❌ Email send failed: {e}")
        return False


# ═══════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════

def main():
    api_key = os.environ.get("RESEND_KEY", "")
    period  = os.environ.get("SCAN_PERIOD", "5y")

    scan_date = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    print(f"\n{'═'*60}")
    print(f"   Gary AI Scanner  |  {scan_date}")
    print(f"   Period: {period}  |  Tickers: {len(WATCHLIST)}")
    print(f"{'═'*60}\n")

    results = scan_all(period=period)

    signals = results[results["conditionA"] == True].to_dict("records")
    errors  = results[results["error"].notna()].to_dict("records")

    # ── terminal summary ─────────────────────────────────────────
    print(f"\n{'─'*60}")
    if signals:
        print(f"   🔔 {len(signals)} conditionA signal(s):")
        for r in signals:
            print(f"     {r['ticker']:<14} {r['name']:<20}  "
                  f"close={r['close']:<8} gp(力度)={r['gp']:<8} days={r['days']:<5} since={r['since_last_gt100']}")
    else:
        print("   今天没有符合条件的个股.")
    if errors:
        print(f"\n  ⚠ {len(errors)} error(s): {', '.join(e['ticker'] for e in errors)}")
    print(f"{'─'*60}\n")

    # ── send email ───────────────────────────────────────────────
    if not api_key:
        print("⚠  RESEND_KEY not set — skipping email.")
        sys.exit(0)

    html, subject = build_html(signals, scan_date, len(WATCHLIST), errors)
    send_email(api_key, html, subject)


if __name__ == "__main__":
    main()
